 version: 2.1
 jobs:
   build:
     docker:
       - image: cimg/node:18.15.0
     steps:
       - checkout
       - run: npm install
       - run: npm test
   test:
     docker:
       - image: cimg/node:18.15.0
     steps:
       - checkout
       - run: npm install
       - run: npm test
 workflows:
   build_and_test:
     jobs:
       - build
       - test:
           requires:
             - build 