 version: 2.1
 orbs:
   node: circleci/node@1.1.6
 jobs:
   build:
     docker:
       - image: circleci/node:18
     steps:
       - checkout
       - run: npm install
       - run: npm test
   test:
     docker:
       - image: circleci/node:18
     steps:
       - checkout
       - run: npm install
       - run: npm test
 workflows:
   build_and_test:
     jobs:
       - build
       - test:
           requires:
             - build 